### ISSUE TITLE
show diff of patched/replaced files so that we know how exactly the fix was implemented

### ISSUE THREAD

**Issue by cjangrist** [AndreV84/mediapipe#3]
PS thank you for this it's incredible help!

**Comment by AndreV84** [comment]
files are the same
the modified file just gets retrieved from this repo as per instruction download url - it has the gstreamer argumentd adjusted for csi
or you are concerned in other file changes?
the rest of the instruction is just list of steps to implement it on jetson, without any modofication, but for minor edit to switch v4l2 driver to nvidiaargus for jetson devkit CSE sensor;
I will try to publish diff little bit later

**Comment by AndreV84** [comment]
@carloshgaray 
Originally it was difference like listed below. However, as the reposotory of mediapipe got updated since the last time I tried implementing it, I will have to release updated patched files.
```
 diff /home/nvidia/dev/mediapipe/demo_run_graph_main_gpu_mod.cc /home/nvidia/ttst/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc
70d69
<  const char* gst =  "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1280, height=720, framerate=30/1 !  nvvidconv ! video/x-raw,format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink";
74c73
<     capture.open(gst, cv::CAP_GSTREAMER);
---
>     capture.open(0);
```
This example only addresses switching from usb camera to CSI sensor.
Another minor patches are the config.guess config.sub files; but they are generated by first run of bazel but the automatically generated files lack some details. you may find original issue here https://github.com/google/mediapipe/issues/470#issuecomment-591463886
Other than that I do not use the opencv script provided by mediapipe but manually assemble the latest version of opencv.
@carloshgaray R U interested in use with nvidia Jetson device?

**Comment by AndreV84** [comment]
@carloshgaray as there is no response from you regarding your concern I am closing the issue; the diff is as follows:
```
 diff demo_run_graph_main_gpu.cc orig/demo_run_graph_main_gpu.cc 
71,72c71
<   const char* gst =  "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1280, height=720, framerate=30/1 !  nvvidconv ! video/x-raw,format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink";
< if (load_video) {
---
>   if (load_video) {
75c74
<     capture.open(gst, cv::CAP_GSTREAMER);
---
>     capture.open(0);

**Comment by AndreV84** [comment]
> PS thank you for this it's incredible help!

```
diff -u /home/nvidia/mediapipe/mediapipe/examples/desktop/orig/demo_run_graph_main_gpu.cc /home/nvidia/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc
--- /home/nvidia/mediapipe/mediapipe/examples/desktop/orig/demo_run_graph_main_gpu.cc	2021-04-21 16:31:39.941459722 -0400
+++ /home/nvidia/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc2021-04-21 15:03:30.674384288 -0400
@@ -68,10 +68,11 @@
   LOG(INFO) << "Initialize the camera or load the video.";
   cv::VideoCapture capture;
   const bool load_video = !absl::GetFlag(FLAGS_input_video_path).empty();
-  if (load_video) {
+  const char* gst =  "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1280, height=720, framerate=30/1 !  nvvidconv ! video/x-raw,format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink";
+if (load_video) {
     capture.open(absl::GetFlag(FLAGS_input_video_path));
   } else {
-    capture.open(0);
+    capture.open(gst, cv::CAP_GSTREAMER);
   }
   RET_CHECK(capture.isOpened());

**Comment by cjangrist** [comment]
> > PS thank you for this it's incredible help!
> 
> ```
> diff -u /home/nvidia/mediapipe/mediapipe/examples/desktop/orig/demo_run_graph_main_gpu.cc /home/nvidia/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc
> --- /home/nvidia/mediapipe/mediapipe/examples/desktop/orig/demo_run_graph_main_gpu.cc	2021-04-21 16:31:39.941459722 -0400
> +++ /home/nvidia/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc2021-04-21 15:03:30.674384288 -0400
> @@ -68,10 +68,11 @@
>    LOG(INFO) << "Initialize the camera or load the video.";
>    cv::VideoCapture capture;
>    const bool load_video = !absl::GetFlag(FLAGS_input_video_path).empty();
> -  if (load_video) {
> +  const char* gst =  "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1280, height=720, framerate=30/1 !  nvvidconv ! video/x-raw,format=BGRx ! videoconvert ! video/x-raw, format=BGR ! appsink";
> +if (load_video) {
>      capture.open(absl::GetFlag(FLAGS_input_video_path));
>    } else {
> -    capture.open(0);
> +    capture.open(gst, cv::CAP_GSTREAMER);
>    }
>    RET_CHECK(capture.isOpened());
> ```

thanks a million this is what I needed!

**Comment by AndreV84** [comment]
@carloshgaray this particular diff only addresses the CSI sensor enablement
the rest of specificities is in installation mediapipe itself on jetson - like pre-requisites install including Bazel, opencv, etc

**Comment by AndreV84** [comment]
@cjangrist 
you may like to chck dockerized examples deployment for jetson
https://github.com/AndreV84/mediapipe#Docker-hand-usb-cam-GPU-example
