### ISSUE TITLE
Patching config files

### ISSUE THREAD

**Issue by JBalhatchet** [AndreV84/mediapipe#6]
At the bazel build step to find the directory for patching the config files, i have no directory ending in /external/com_github_glog_glog/, and do not have a config.sub file anywhere within the /external/ directory. 

I have only a config.guess file within /external/llvm-raw/llvm/cmake

Can you suggest another way to find where to replace the config files / where else they may be / whether it may have been some sort of versioning issue? 
I am running bazel version 4.0.0 as in the previous step, but running openjdk-11, as my bazel compilation would fail on jdk-8. 

Do you suggest going back to jdk-8 and trying other ways to resolve the failure? 

Thank-you

**Comment by AndreV84** [comment]
@JBalhatchet with more recent versions of the mediapipe/ basel the specified patching step can be disregarded, just go on to the next steps]
