### ISSUE TITLE
Tensorrt inference

### ISSUE THREAD

**Issue by Gaozhongpai** [AndreV84/mediapipe#7]
Hi @AndreV84, have you tried tensorrt inference in mediapipe?

**Comment by AndreV84** [comment]
@Gaozhongpai That is a great question!
I just used tensorflow gpu implementation. I doubt it uses TensorRT

**Comment by AndreV84** [comment]
these folks trioed tensorrt
https://github.com/houmo-ai/mediapipe_plus
you may also check the https://github.com/google/mediapipe/issues/723

**Comment by AndreV84** [comment]
@Gaozhongpai 
They used to suggest 
```
bazel build -c opt --config=cuda --spawn_strategy=local \
    --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS \
    --action_env TF_NEED_TENSORRT=1 \
    mediapipe/examples/desktop/object_detection:object_detection_tensorflow
```
source 
https://github.com/google/mediapipe/issues/723#issuecomment-632224493

**Comment by Gaozhongpai** [comment]
> @Gaozhongpai That is a great question!
> 
> I just used tensorflow gpu implementation. I doubt it uses TensorRT
> 
> 

I tried to use yolov7 tflite. tensorflow gpu doesn't support several operations including transpose, split, etc., in yolov7.
