### ISSUE TITLE
Bazel and Mediapipe Version

### ISSUE THREAD

**Issue by VieiraJardel** [AndreV84/mediapipe#8]
In which step do I configure the version of MediaPipe I want to install?

I'm facing this problem when I try building and Running an example:
jv@jv-desktop:~/mediapipe$ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
ERROR: /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/crosstool/setup.bzl:69:32: name 'module_extension' is not defined
ERROR: error loading package '': in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_rules_swift/swift/extras.bzl: in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/lib/repositories.bzl: Extension 'crosstool/setup.bzl' has errors
INFO: Elapsed time: 0,323s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by AndreV84** [comment]
try to use tested versions : " 089 mediapipe with 4.2.1 bazel"

**Comment by VieiraJardel** [comment]
Where do I configure to build MediaPipe 0.8.9?

**Comment by VieiraJardel** [comment]
I tried to use Bazel 4.2.1, but I faced the same problem:
jv@jv-desktop:~/mediapipe$ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
Starting local Bazel server and connecting to it...
WARNING: ignoring LD_PRELOAD in environment.
ERROR: /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/crosstool/setup.bzl:69:32: name 'module_extension' is not defined
ERROR: error loading package '': in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_rules_swift/swift/extras.bzl: in /home/jv/.cache/bazel/_bazel_jv/e1c4a6250c6ceb5a498b3a5ff767dd81/external/build_bazel_apple_support/lib/repositories.bzl: Extension 'crosstool/setup.bzl' has errors
INFO: Elapsed time: 9,991s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Maybe the problem can be solved by updating Bazel to the latest version, but I might encounter compatibility issues with MediaPipe :-/

**Comment by AndreV84** [comment]
the proposed solution is to use :  " 0.8.9 mediapipe release with 4.2.1 bazel"

did your setup meet both conditions? or only the latter of the two?

**Comment by VieiraJardel** [comment]
I just changed the Bazel version because I don't know how to change the MediaPipe version. At which step can I adjust the MediaPipe version?

**Comment by VieiraJardel** [comment]
It works! I'm sorry, I didn't know how to download MediaPipe 0.8.9. With this version, THIS problem was solved.

**Comment by xcjcb001** [comment]
i faced the same problem ,   mediapepe 0.10.9   bazel 4.2.2    i want to  use mediapipe 0.10.9  .  what should i do?
